"""
Schema demo
"""
from jsonschema_inference.schema.objs import DynamicRecord, Record, Atomic, Array, Optional, Unknown, UniformRecord
from collections import Counter

DynamicRecord({'last_serial': Atomic(int),
               'info': Record({'author': Atomic(str),
                               'author_email': Atomic(str),
                               'bugtrack_url': Atomic(None),
                               'classifiers': Array(Atomic(str)),
                               'description': Atomic(str),
                               'description_content_type': Optional(Atomic(str)),
                               'docs_url': Atomic(None),
                               'download_url': Atomic(str),
                               'downloads': Record({'last_day': Atomic(int),
                                                    'last_month': Atomic(int),
                                                    'last_week': Atomic(int)}),
                               'home_page': Atomic(str),
                               'keywords': Optional(Atomic(str)),
                               'license': Atomic(str),
                               'maintainer': Optional(Atomic(str)),
                               'maintainer_email': Optional(Atomic(str)),
                               'name': Atomic(str),
                               'package_url': Atomic(str),
                               'platform': Optional(Atomic(str)),
                               'project_url': Atomic(str),
                               'project_urls': Optional(DynamicRecord({'Issue tracker': Atomic(str),
                                                                       'Homepage': Atomic(str),
                                                                       'Source': Atomic(str),
                                                                       'Documentation': Atomic(str),
                                                                       'Download': Atomic(str),
                                                                       'Bug Tracker': Atomic(str),
                                                                       'Bug Reports': Atomic(str),
                                                                       'Repository': Atomic(str)},
                                                                      Counter({'Homepage': 77,
                                                                               'Download': 17,
                                                                               'Bug Tracker': 6,
                                                                               'Bug Reports': 1,
                                                                               'Source': 1,
                                                                               'Repository': 1,
                                                                               'Documentation': 1,
                                                                               'Issue tracker': 1}))),
                               'release_url': Atomic(str),
                               'requires_dist': Optional(Array(Atomic(str))),
                               'requires_python': Optional(Atomic(str)),
                               'summary': Atomic(str),
                               'version': Atomic(str),
                               'yanked': Atomic(bool),
                               'yanked_reason': Atomic(None)}),
               'releases': UniformRecord(Array(Record({'comment_text': Atomic(str),
                                                       'digests': Record({'blake2b_256': Atomic(str),
                                                                          'md5': Atomic(str),
                                                                          'sha256': Atomic(str)}),
                                                       'downloads': Atomic(int),
                                                       'filename': Atomic(str),
                                                       'has_sig': Atomic(bool),
                                                       'md5_digest': Atomic(str),
                                                       'packagetype': Atomic(str),
                                                       'python_version': Atomic(str),
                                                       'requires_python': Optional(Atomic(str)),
                                                       'size': Atomic(int),
                                                       'upload_time': Atomic(str),
                                                       'upload_time_iso_8601': Atomic(str),
                                                       'url': Atomic(str),
                                                       'yanked': Atomic(bool),
                                                       'yanked_reason': Atomic(None)}))),
               'urls': Array(Record({'comment_text': Atomic(str),
                                     'digests': Record({'blake2b_256': Atomic(str),
                                                        'md5': Atomic(str),
                                                        'sha256': Atomic(str)}),
                                     'downloads': Atomic(int),
                                     'filename': Atomic(str),
                                     'has_sig': Atomic(bool),
                                     'md5_digest': Atomic(str),
                                     'packagetype': Atomic(str),
                                     'python_version': Atomic(str),
                                     'requires_python': Optional(Atomic(str)),
                                     'size': Atomic(int),
                                     'upload_time': Atomic(str),
                                     'upload_time_iso_8601': Atomic(str),
                                     'url': Atomic(str),
                                     'yanked': Atomic(bool),
                                     'yanked_reason': Atomic(None)})),
               'vulnerabilities': Array(Unknown()),
               'message': Atomic(str)},
              Counter({'info': 61,
                       'last_serial': 61,
                       'releases': 61,
                       'urls': 61,
                       'vulnerabilities': 61,
                       'message': 6}))
