"""
Schema demo
"""
from jsonschema_inference.schema.objs import DynamicDict, Dict, Simple, List, Optional, Unknown, UniformDict, Counter

DynamicDict({'info': Dict({'author': Simple(str),
                           'author_email': Simple(str),
                           'bugtrack_url': Simple(None),
                           'classifiers': List(Simple(str)),
                           'description': Simple(str),
                           'description_content_type': Optional(Simple(str)),
                           'docs_url': Simple(None),
                           'download_url': Optional(Simple(str)),
                           'downloads': Dict({'last_day': Simple(int),
                                              'last_month': Simple(int),
                                              'last_week': Simple(int)}),
                           'home_page': Simple(str),
                           'keywords': Optional(Simple(str)),
                           'license': Simple(str),
                           'maintainer': Optional(Simple(str)),
                           'maintainer_email': Optional(Simple(str)),
                           'name': Simple(str),
                           'package_url': Simple(str),
                           'platform': Optional(Simple(str)),
                           'project_url': Simple(str),
                           'project_urls': Optional(DynamicDict({'Homepage': Simple(str),
                                                                 'Bug Tracker': Simple(str),
                                                                 'Changes': Simple(str),
                                                                 'Download': Simple(str),
                                                                 'Source': Simple(str),
                                                                 'Source Code': Simple(str),
                                                                 'Documentation': Simple(str),
                                                                 'Repository': Simple(str)},
                                                                Counter({'Homepage': 19,
                                                                         'Download': 9,
                                                                         'Source': 2,
                                                                         'Documentation': 2,
                                                                         'Repository': 2,
                                                                         'Bug Tracker': 2,
                                                                         'Changes': 1,
                                                                         'Source Code': 1}))),
                           'release_url': Simple(str),
                           'requires_dist': Optional(List(Simple(str))),
                           'requires_python': Optional(Simple(str)),
                           'summary': Simple(str),
                           'version': Simple(str),
                           'yanked': Simple(bool),
                           'yanked_reason': Simple(None)}),
             'releases': UniformDict(List(Dict({'comment_text': Simple(str),
                                                'digests': Dict({'md5': Simple(str),
                                                                 'sha256': Simple(str)}),
                                                'downloads': Simple(int),
                                                'filename': Simple(str),
                                                'has_sig': Simple(bool),
                                                'md5_digest': Simple(str),
                                                'packagetype': Simple(str),
                                                'python_version': Simple(str),
                                                'requires_python': Optional(Simple(str)),
                                                'size': Simple(int),
                                                'upload_time': Simple(str),
                                                'upload_time_iso_8601': Simple(str),
                                                'url': Simple(str),
                                                'yanked': Simple(bool),
                                                'yanked_reason': Simple(None)}))),
             'vulnerabilities': List(Unknown()),
             'urls': List(Dict({'comment_text': Simple(str),
                                'digests': Dict({'md5': Simple(str),
                                                 'sha256': Simple(str)}),
                                'downloads': Simple(int),
                                'filename': Simple(str),
                                'has_sig': Simple(bool),
                                'md5_digest': Simple(str),
                                'packagetype': Simple(str),
                                'python_version': Simple(str),
                                'requires_python': Optional(Simple(str)),
                                'size': Simple(int),
                                'upload_time': Simple(str),
                                'upload_time_iso_8601': Simple(str),
                                'url': Simple(str),
                                'yanked': Simple(bool),
                                'yanked_reason': Simple(None)})),
             'last_serial': Simple(int),
             'message': Simple(str)},
            Counter({'info': 4,
                     'last_serial': 4,
                     'releases': 4,
                     'urls': 4,
                     'vulnerabilities': 4,
                     'message': 3}))
