name: Run tests

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: run tests
        run: | 
          pip install pytest
          pytest
      - name: run type checking
        run: | 
         pip install mypy
         pip install types-requests
         mypy jsonschema_inference --ignore-missing-imports
      - name: flake8 checking
        run: |
         pip install flake8
         flake8 --ignore=E501,W504